### ISSUE TITLE
TypeError if the Model belongs to User and without authentication

### ISSUE THREAD

**Issue by guham** [Rodmg/flugzeug#7]
### How to reproduce
1. Add a new route
```bash
# with the api command:
$ flug api

Welcome to the Flugzeug API generator

? Model name: Test
? Would you like your model to belong to User? Yes
? Controller name: Test
? API Version: v1
? Needs authentication? No
   create app/models/Test.ts
   create app/controllers/v1/Test.ts


# or with the controller command:
$ flug controller

Welcome to the Flugzeug Controller generator

? Controller name: Test
? Model: Test
? API Version: v1
? Needs authentication? No
? Does the model belongs to User? Yes
   create app/controllers/v1/Test.ts
```
2. then call it
```bash
curl --location --request GET 'http://localhost:8888/api/v1/test' \
--header 'Accept: application/json'
```
### Result
```
TypeError: Cannot read property 'id' of undefined
    at flug/app/policies/General.ts:56:32
```

### Problem

The `req.session` object is initialized in the `Controller` class, so it is available for all the next middleware. `filterOwner`, `appendUser`, `filterRoles` and `isSelfUser` middlewares use it to retrieve information about the user (from the JWT). But the `req.session.jwt` object is populated only when the `validateJWT` middleware is used when defining the route, which is not the case when the user chooses not to use authentication during the setup.

**Comment by guham** [comment]
There are at least two solutions:
- if the user decides that the new model should belong to the User then the `validateJWT` must be added and the `Needs authentication?` question removed (`needsAuth` will be set to true)
- do not use `belongsToUser` parameter to add middlewares in the route definition, but rather introduce a new parameter in the setup (=> new question, something like "Filter by user?").

I'm willing to submit a PR to fix this issue, just waiting for your feedback :)

**Comment by Rodmg** [comment]
Thanks for reporting, in this case, If the controller doesn’t need auth, we should remove the appendUser and filterOwner middlewares, and the user would be expected to manually specify the owner in the request.

**Comment by Rodmg** [comment]
@guham if you can submit a PR with the changes for removing the appendUser and filterOwner middlewares if we are not using auth it would be greatly appreciated. this will involve modifying the template for the controller generator.
